# --- TABELA CUSTOMERS ---
[tables.customers]

  [[tables.customers.columns]]
  name = "id"
  strategy = "random_uuid"

  [[tables.customers.columns]]
  name = "name"
  strategy = "faker_name"

  [[tables.customers.columns]]
  name = "document"
  strategy = "cpf" 

  [[tables.customers.columns]]
  name = "phone"
  strategy = "faker_phone_br"

  [[tables.customers.columns]]
  name = "status"
  strategy = "random_choice"
  options = ["ACTIVE", "INACTIVE", "PENDING", "DELETED"]

# --- TABELA SERVER_LOGS ---
[tables.server_logs]

  [[tables.server_logs.columns]]
  name = "ip_address"
  strategy = "faker_ip"

  [[tables.server_logs.columns]]
  name = "access_token"
  strategy = "random_string"
  length = 32

  [[tables.server_logs.columns]]
  name = "internal_code"
  strategy = "nullify"

# --- TABELA SALES ---
[tables.sales]

  [[tables.sales.columns]]
  name = "category"
  strategy = "fixed"
  value = "GENERAL_MERCHANDISE"

  [[tables.sales.columns]]
  name = "value"
  strategy = "dp_laplace"
  epsilon = 0.3
  sensitivity = 500.0